pipeline:
  build:
    image: backstopjs/backstopjs
    environment:
      - NODE_ENV=production
    commands: 
      - export BRANCH_ENV=$${DRONE_COMMIT_BRANCH}
      - echo $NODE_ENV
      - echo $BRANCH_ENV