pipeline:
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
       A build for {{repo.name}} {{build.number}} for {{build.branch}} has started.
  frontend:
    image: backstopjs/backstopjs
    commands: 
      - npm install
      - npm run lint
      - npm run dev
      - npm run test
    mem_limit: 2000MB 
    when:
      branch: master
  s3-sync:
    image: plugins/s3-sync:1
    region: us-west-2
    bucket: dev.merqbiz.com
    source: public
    target: /
    acl:
      "*": public-read
    content_encoding:
      ".js": gzip
      ".css": gzip
    cloudfront_distribution: E1CH3B6EW4M6KZ
    secrets: [ aws_access_key_id, aws_secret_access_key ]
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
     {{#success build.status}}
       A build for {{repo.name}} {{build.number}} for {{build.branch}} succeeded. Good job.
     {{else}}
       A build for {{repo.name}} {{build.number}} failed. Fix me please.
     {{/success}}