pipeline:
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      Continuous integration started for ${DRONE_REPO}${DRONE_REPO} {{build.branch}} committed for {{repo.name}} {{build.number}}.
  frontend:
    image: plugins/docker
    dockerfile: ./Dockerfile
    environment:
      - npm_config_unsafe_perm=true
    commands:
      - npm install
      - npm run build
      - npm run test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
     {{#success build.status}}
       A build for {{repo.name}} {{build.number}} for {{build.branch}} succeeded. Good job.
     {{else}}
       A build for {{repo.name}} {{build.number}} failed. Fix me please.
     {{/success}}