pipeline:
  build-image:
    image: plugins/ecr
    repo: 784985187312.dkr.ecr.us-west-2.amazonaws.com/merqbiz-public-pages
    registry: 784985187312.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    dockerfile: Dockerfile
    storage_driver: overlay
    build_args:
      - BRANCH_ENV=$${DRONE_COMMIT_BRANCH}
    tags:
      - 1.0.${DRONE_BUILD_NUMBER}
    secrets: [ ecr_access_key, ecr_secret_key ]
  