pipeline:
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      Continuous integration started for ${DRONE_REPO}${DRONE_REPO} {{build.branch}} committed for {{repo.name}} {{build.number}}.
  test:
    image: plugins/docker
    dockerfile: ./Dockerfile
    commands:
      - npm install
      - npm run build
      - npm run test
  notify:
    image: plugins/slack
    username: merqbizbuddyhoward
    channel: sandbox_tran
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
     {{#success build.status}}
       A build for {{repo.name}} {{build.number}} for {{build.branch}} succeeded. Good job.
     {{else}}
       A build for {{repo.name}} {{build.number}} failed. Fix me please.
     {{/success}}