pipeline:
  build:
    image: backstopjs/backstopjs
    environment:
      - NODE_ENV=production
      - BRANCH_ENV=${DRONE_REPO_BRANCH}
    commands: 
      - npm install
      - echo $NODE_ENV
      - echo $BRANCH_ENV