pipeline:
  test-run:
    image: backstopjs/backstopjs
    commands: 
      - npm install
      - npm run build
      - backstop test --config="backstop/backstop-config.js"
  test-report:
    image: plugins/s3-sync:1
    region: us-west-2
    bucket: dev.merq.biz
    source: backstop_data
    target: /tests/${DRONE_BUILD_NUMBER}
    acl:
      "*": public-read
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      status: [ failure, success ]
  deploy-dev:
    image: plugins/s3-sync:1
    region: us-west-2
    bucket: dev2.merqbiz.com
    source: public
    target: /
    acl:
      "*": public-read
    content_encoding:
      ".js": gzip
      ".css": gzip
    cloudfront_distribution: E1CH3B6EW4M6KZ
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      branch: [develop]
      status: [ success, failure ]
  deploy-notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      branch: [develop, qa]
    template: >
     {{#success build.status}}
       Deployment for {{repo.name}} {{build.number}} for {{build.branch}} succeeded. Good job!
       Test report https://s3-us-west-2.amazonaws.com/dev.merq.biz/tests/${DRONE_BUILD_NUMBER}/html_report/index.html
     {{else}}
       Deployment for {{repo.name}} {{build.number}} failed. Fix me please!
       Test report https://s3-us-west-2.amazonaws.com/dev.merq.biz/tests/${DRONE_BUILD_NUMBER}/html_report/index.html
     {{/success}}